services:
  postgres:  # Только если используете PostgreSQL
    image: postgres:15
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql://botuser:botpass@postgres:5432/botdb
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
