version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Это для сохранения данных базы
    ports:
      - "5432:5432" # Опционально, если вам нужен доступ к БД снаружи
    restart: unless-stopped

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app # Это монтирует весь ваш текущий каталог в /app внутри контейнера
      - ./images:/app/images # <--- ДОБАВЬТЕ ЭТУ СТРОКУ для изображений!
    restart: on-failure # Можно изменить на unless-stopped, если хотите, чтобы бот всегда пытался перезапуститься