services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot: # <-- ДОЛЖНО БЫТЬ РОВНО ДВА ПРОБЕЛА ЗДЕСЬ, КАК И В DB
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "80:80"
    command: python bot.py # <-- ДОЛЖНО БЫТЬ ЧЕТЫРЕ ПРОБЕЛА ЗДЕСЬ (относительно начала строки), ЕСЛИ ИСПОЛЬЗУЕТЕ 2-ПРОБЕЛЬНЫЙ ОТСТУП

  init_db: # <-- ДОЛЖНО БЫТЬ РОВНО ДВА ПРОБЕЛА ЗДЕСЬ
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "python database.py && python fill_products.py"
    profiles: ["setup"]

volumes: # <-- БЕЗ ОТСТУПА
  db_data: # <-- ДВА ПРОБЕЛА