services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "80:80"
    command: python bot.py

  init_db:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    # ЭТО НОВОЕ ДОБАВЛЕНИЕ: init_db будет использовать базу "postgres" для подключения
    # Это позволит ему создать вашу базу "petshop_db"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/postgres
    command: bash -c "python database.py && python fill_products.py"
    profiles: ["setup"]

volumes:
  db_data:
